=== MobilityData/mobility-database-catalogs/schemas/gtfs_realtime_source_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "The GTFS Realtime source schema of the Mobility Catalogs.",
  "type": "object",
  "properties": {
    "mdb_source_id": {
      "type": "number",
      "description": "Unique numerical identifier."
    },
    "data_type": {
      "type": "string",
      "description": "The data format that the source uses, e.g gtfs, gtfs-rt.",
      "enum": ["gtfs-rt"]
    },
    "entity_type": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": ["vp", "tu", "sa"]
      },
      "description": "The feed entity types (abbreviated) available in the source: vp (vehicle positions), tu (trip updates) and sa (service alerts)."
    },
    "provider": {
      "type": "string",
      "description": "Name of the transit provider."
    },
    "name": {
      "type": "string",
      "description": "An optional description of the data source, e.g to specify if the data source is an aggregate of multiple providers, or which network is represented by the source."
    },
    "feed_contact_email": {
      "type": "string",
      "description": "An email to use to contact the provider of the feed."
    },
    "static_reference": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "A list of the static sources that the real time source is associated with, represented by their MDB source IDs. Although optional, if not provided, the location of this source will be set to unknown."
    },
    "features": {
      "type": "array",
      "description": "A list of features that the source supports.",
      "items": {
        "type": "string",
        "enum": ["occupancy"]
      }
    },
    "status": {
      "type": "string",
      "description": "The status of the source which can be used to determine if/how to include it in public trip-planning. If not provided, source is assumed to be active. Should be one of: active: The source is active and should be included in public trip-planning. inactive: The source is inactive / hasn't been updated recently and should be included in public trip-planning at risk of providing outdated information. deprecated: The source is explicitly deprecated and should not be included in public trip-planning. development: The source is in development or being used to test a specific feature and should not be included in public trip-planning.",
      "enum": ["active","deprecated","inactive","development"]
    },
    "note": {
      "type": "string",
      "description": "A note to clarify complex use cases for consumers, for example when several static sources are represented in a realtime source."
    },
    "urls": {
      "type": "object",
      "properties": {
        "direct_download": {
          "type": "string",
          "description": "URL that automatically opens the source.",
          "pattern": "^(http|https|ftp):\/\/[a-zA-Z0-9.,~#{}():&/%='?_+/-]+$"
        },
        "authentication_type": {
          "type": "number",
          "description": "The authentication type of the source.",
          "enum": [
            0,
            1,
            2,
            3
          ]
        },
        "authentication_info": {
          "type": "string",
          "description": "If authentication is required, this field contains a URL to a human-readable page describing how the authentication should be performed and how credentials can be created. This field is required for `authentication_type=1` or greater.",
          "pattern": "^(http|https|ftp):\/\/[a-zA-Z0-9.,~#{}():&/%='?_+/-]+$"
        },
        "api_key_parameter_name": {
          "type": "string",
          "description": "This field defines the name of the parameter to pass in the URL to provide the API key. This field is required for `authentication_type=1` and `authentication_type=2`."
        },
        "license": {
          "type": "string",
          "description": "The transit providerâ€™s license information.",
          "pattern": "^(http|https|ftp):\/\/[a-zA-Z0-9.,~#{}():&/%='?_+/-]+$"
        }
      },
      "oneOf": [
        {
          "not": {
            "required": [
              "authentication_type"
            ]
          }
        },
        {
          "allOf": [
            {
              "if": {
                "properties": {
                  "authentication_type": {
                    "enum": [
                      1,
                      2,
                      3
                    ]
                  }
                }
              },
              "then": {
                "required": [
                  "authentication_info"
                ]
              },
              "else": {
                "not": {
                  "required": [
                    "authentication_info"
                  ]
                }
              }
            },
            {
              "if": {
                "properties": {
                  "authentication_type": {
                    "enum": [
                      1,
                      2
                    ]
                  }
                }
              },
              "then": {
                "required": [
                  "api_key_parameter_name"
                ]
              },
              "else": {
                "not": {
                  "required": [
                    "api_key_parameter_name"
                  ]
                }
              }
            }
          ]
        }
      ],
      "required": [
        "direct_download"
      ]
    },
    "redirect": {
      "type": "array",
      "description": "A list of feed IDs that should be used as a replacement for this feed.",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "description": "The target feed id of that redirect."
          },
          "comment": {
            "type": "string",
            "description": "A comment explaining the redirect."
          }
        }
      }
    }
  },
  "required": ["mdb_source_id", "data_type", "entity_type", "provider", "urls"]
}

=== MobilityData/mobility-database-catalogs/catalogs/sources/gtfs/realtime/pl-slaskie-zarzad-transportu-metropolitalnego-gtfs-rt-tu-1821.json
{
    "mdb_source_id": 1821,
    "data_type": "gtfs-rt",
    "entity_type": [
        "tu"
    ],
    "provider": "ZarzÄ…d Transportu Metropolitalnego",
    "static_reference": [
        "1819"
    ],
    "urls": {
        "direct_download": "http://gtfsrt.metropoliagzm.pl:1111/gtfsrt/gzm/tripUpdates",
        "license": "https://otwartedane.metropoliagzm.pl/en/dataset/rozklady-jazdy-i-lokalizacja-przystankow-gtfs-rt/resource/07aedb72-2464-4052-a380-0d45426fd83b?inner_span=True"
    }
}

=== MobilityData/mobility-database-catalogs/catalogs/sources/gtfs/realtime/us-california-foothill-transit-gtfs-rt-vp-2229.json
{
    "mdb_source_id": 2229,
    "data_type": "gtfs-rt",
    "entity_type": [
        "vp"
    ],
    "provider": "Foothill Transit",
    "static_reference": [
        "101"
    ],
    "urls": {
        "direct_download": "https://foothill_3rdparty.rideralerts.com/myStop/GTFS-Realtime.ashx?&Type=VehiclePosition&serverid=0",
        "authentication_type": 0,
        "license": "https://www.foothilltransit.org/about/developer-resources/developer-license-agreement/"
    }
}

=== MobilityData/mobility-database-catalogs/catalogs/sources/gtfs/realtime/us-district-of-columbia-washington-metropolitan-area-transit-authority-wmata-gtfs-rt-sa-1848.json
{
    "mdb_source_id": 1848,
    "data_type": "gtfs-rt",
    "entity_type": [
        "sa"
    ],
    "provider": "Washington Metropolitan Area Transit Authority (WMATA)",
    "static_reference": [
        "1846"
    ],
    "note": "bus",
    "urls": {
        "direct_download": "https://api.wmata.com/gtfs/bus-gtfsrt-alerts.pb",
        "authentication_type": 1,
        "authentication_info": "https://developer.wmata.com/signup/",
        "api_key_parameter_name": "api_key",
        "license": "https://developer.wmata.com/license"
    }
}

=== MobilityData/mobility-database-catalogs/catalogs/sources/gtfs/realtime/us-new-york-metro-north-railroad-gtfs-rt-tu-1627.json
{
    "mdb_source_id": 1627,
    "data_type": "gtfs-rt",
    "entity_type": [
        "tu"
    ],
    "provider": "Metropolitan Transit Authority (MTA)",
    "name": "Metro North Railroad",
    "static_reference": [
        "524"
    ],
    "urls": {
        "direct_download": "https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds/mnr%2Fgtfs-mnr",
        "authentication_type": 0,
        "license": "https://api.mta.info/#/DataFeedAgreement"
    }
}

=== MobilityData/mobility-database-catalogs/catalogs/sources/gtfs/realtime/us-california-regional-transportation-commission-of-southern-nevada-rtc-gtfs-rt-sa-1667.json
{
    "mdb_source_id": 1667,
    "data_type": "gtfs-rt",
    "entity_type": [
        "sa"
    ],
    "provider": "Regional Transportation Commission of Southern Nevada (RTC)",
    "static_reference": [
        "110"
    ],
    "urls": {
        "direct_download": "https://api.goswift.ly/real-time/las-vegas-rtc/gtfs-rt-alerts/",
        "authentication_type": 2,
        "authentication_info": "https://goswift.ly/realtime-api-key",
        "api_key_parameter_name": "authorization",
        "license": "https://www.goswift.ly/api-license"
    }
}

=== MobilityData/mobility-database-catalogs/catalogs/sources/gtfs/realtime/ca-alberta-edmonton-transit-system-gtfs-rt-vp-1496.json
{
    "mdb_source_id": 1496,
    "data_type": "gtfs-rt",
    "entity_type": [
        "vp"
    ],
    "provider": "Edmonton Transit System",
    "static_reference": [
        "714"
    ],
    "urls": {
        "direct_download": "http://gtfs.edmonton.ca/TMGTFSRealTimeWebService/Vehicle/VehiclePositions.pb",
        "authentication_type": 0,
        "license": "https://www.edmonton.ca/transportation/Web-version2.1-OpenDataAgreement.pdf"
    }
}

=== MobilityData/mobility-database-catalogs/catalogs/sources/gtfs/realtime/us-pennsylvania-port-authority-of-allegheny-county-bus-gtfs-rt-vp-1714.json
{
    "mdb_source_id": 1714,
    "data_type": "gtfs-rt",
    "entity_type": [
        "vp"
    ],
    "provider": "Port Authority of Allegheny County",
    "name": "Port Authority of Allegheny County Bus",
    "static_reference": [
        "409"
    ],
    "urls": {
        "direct_download": "https://truetime.portauthority.org/gtfsrt-bus/vehicles",
        "authentication_type": 0,
        "license": "https://www.portauthority.org/business-center/developer-resources/developer-license-agreement/"
    }
}

=== MobilityData/mobility-database-catalogs/catalogs/sources/gtfs/realtime/ca-british-columbia-bc-transit-regional-district-of-nanaimo-rdn-transit-system-gtfs-rt-tu-1404.json
{
    "mdb_source_id": 1404,
    "data_type": "gtfs-rt",
    "entity_type": [
        "tu"
    ],
    "provider": "BC Transit - Regional District of Nanaimo (RDN) Transit System",
    "status": "deprecated",
    "static_reference": [
        "692"
    ],
    "urls": {
        "direct_download": "http://nanaimo.mapstrat.com/current/gtfrealtime_TripUpdates.bin",
        "authentication_type": 0,
        "license": "https://www.bctransit.com/open-data/terms-of-use"
    },
    "redirect": [
        {
            "id": "2475",
            "comment": " "
        }
    ]
}
