=== MobilityData/mobility-database-catalogs/schemas/gtfs_schedule_source_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "The GTFS Schedule source schema of the Mobility Catalogs.",
  "type": "object",
  "properties": {
    "mdb_source_id": {
      "type": "number",
      "description": "Unique numerical identifier."
    },
    "data_type": {
      "type": "string",
      "description": "The data format that the source uses, e.g gtfs, gtfs-rt.",
      "enum": ["gtfs"]
    },
    "provider": {
      "type": "string",
      "description": "Name of the transit provider."
    },
    "name": {
      "type": "string",
      "description": "An optional description of the data source, e.g to specify if the data source is an aggregate of multiple providers, or which network is represented by the source."
    },
    "feed_contact_email": {
      "type": "string",
      "description": "An email to use to contact the provider of the feed."
    },
    "location": {
      "type": "object",
      "description": "The location information of the source.",
      "properties": {
        "country_code": {
          "type": "string",
          "description": "ISO 3166-1 alpha-2 code designating the country where the system is located."
        },
        "subdivision_name": {
          "type": "string",
          "description": "ISO 3166-2 subdivision name designating the subdivision (e.g province, state, region) where the system is located."
        },
        "municipality": {
          "type": "string",
          "description": "Primary municipality in which the transit system is located."
        },
        "bounding_box": {
          "type": "object",
          "description": "This is the bounding box of the data source when it was first added to the catalog. It includes the date and timestamp the bounding box was extracted in UTC.",
          "oneOf": [
            {
              "properties": {
                "minimum_latitude": {
                  "type": "number",
                  "minimum": -90,
                  "maximum": 90
                },
                "maximum_latitude": {
                  "type": "number",
                  "minimum": -90,
                  "maximum": 90
                },
                "minimum_longitude": {
                  "type": "number",
                  "minimum": -180,
                  "maximum": 180
                },
                "maximum_longitude": {
                  "type": "number",
                  "minimum": -180,
                  "maximum": 180
                },
                "extracted_on": {
                  "type": "string",
                  "format": "date-time"
                }
              }
            },
            {
              "properties": {
                "minimum_latitude": {
                  "type": "null"
                },
                "maximum_latitude": {
                  "type": "null"
                },
                "minimum_longitude": {
                  "type": "null"
                },
                "maximum_longitude": {
                  "type": "null"
                },
                "extracted_on": {
                  "type": "string",
                  "format": "date-time"
                }
              }
            }
          ],
          "required": ["minimum_latitude", "maximum_latitude", "minimum_longitude", "maximum_longitude", "extracted_on"]
        }
      },
      "required": ["country_code", "bounding_box"]
    },
    "features": {
      "type": "array",
      "description": "A list of features that the source supports.",
      "items": {
        "type": "string",
        "enum": ["fares-v2","fares-v1","flex-v1","flex-v2","pathways"]
      }
    },
    "status": {
      "type": "string",
      "description": "The status of the source which can be used to determine if/how to include it in public trip-planning. If not provided, source is assumed to be active. Should be one of: active: The source is active and should be included in public trip-planning. inactive: The source is inactive / hasn't been updated recently and should be included in public trip-planning at risk of providing outdated information. deprecated: The source is explicitly deprecated and should not be included in public trip-planning. development: The source is in development or being used to test a specific feature and should not be included in public trip-planning.",
      "enum": ["active","deprecated","inactive","development"]
    },
    "urls": {
      "type": "object",
      "properties": {
        "direct_download": {
          "type": "string",
          "description": "URL that automatically opens the source.",
          "pattern": "^(http|https|ftp):\/\/[a-zA-Z0-9.,~#{}():&/%='?_+/-]+$"
        },
        "authentication_type": {
          "type": "number",
          "description": "The authentication type of the source.",
          "enum": [
            0,
            1,
            2
          ]
        },
        "authentication_info": {
          "type": "string",
          "description": "If authentication is required, this field contains a URL to a human-readable page describing how the authentication should be performed and how credentials can be created. This field is required for `authentication_type=1` and `authentication_type=2`.",
          "pattern": "^(http|https|ftp):\/\/[a-zA-Z0-9.,~#{}():&/%='?_+/-]+$"
        },
        "api_key_parameter_name": {
          "type": "string",
          "description": "This field defines the name of the parameter to pass in the URL to provide the API key. This field is required for `authentication_type=1` and `authentication_type=2`."
        },
        "latest": {
          "type": "string",
          "description": "A stable URL for the latest dataset of a source.",
          "pattern": "^(http|https|ftp):\/\/[a-zA-Z0-9.,~#{}():&/%='?_+/-]+$"
        },
        "license": {
          "type": "string",
          "description": "The transit provider’s license information.",
          "pattern": "^(http|https|ftp):\/\/[a-zA-Z0-9.,~#{}():&/%='?_+/-]+$"
        }
      },
      "oneOf": [
        {
          "not": {
            "required": [
              "authentication_type"
            ]
          }
        },
        {
          "if": {
            "properties": {
              "authentication_type": {
                "enum": [
                  1,
                  2
                ]
              }
            }
          },
          "then": {
            "required": [
              "authentication_info",
              "api_key_parameter_name"
            ]
          },
          "else": {
            "not": {
              "required": [
                "authentication_info",
                "api_key_parameter_name"
              ]
            }
          }
        }
      ],
      "required": ["direct_download", "latest"]
    },
    "redirect": {
      "type": "array",
      "description": "A list of feed IDs that should be used as a replacement for this feed.",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "description": "The target feed id of that redirect."
          },
          "comment": {
            "type": "string",
            "description": "A comment explaining the redirect."
          }
        }
      }
    },
    "is_official": {
      "type": "string",
      "description": "True if a feed comes directly from the agency, False if a feed is created by researchers or partners unaffiliated with the agency or municipality.",
      "enum": ["True","False"]
    },
    "is_producer_url_unstable": {
      "type": ["string", "null"],
      "description": "True if the producer URL is known to be unstable (e.g. changes frequently), False otherwise.",
      "enum": [null, "True", "False"]
    }
  },
  "required": ["mdb_source_id", "data_type", "provider", "location", "urls"]
}

=== MobilityData/mobility-database-catalogs/catalogs/sources/gtfs/schedule/us-virginia-star-transit-flex-gtfs-2444.json
{
    "mdb_source_id": 2444,
    "data_type": "gtfs",
    "provider": "STAR Transit",
    "is_official": "True",
    "feed_contact_email": "support+startransit-va-us@trilliumtransit.com", 
    "name": "Flex",
    "location": {
        "country_code": "US",
        "subdivision_name": "Virginia",
        "bounding_box": {
            "minimum_latitude": null,
            "maximum_latitude": null,
            "minimum_longitude": null,
            "maximum_longitude": null,
            "extracted_on": "2025-04-09T17:57:45+00:00"
        }
    },
    "urls": {
        "direct_download": "https://data.trilliumtransit.com/gtfs/startransit-va-us/startransit-va-us--flex-v2.zip",
        "latest": "https://storage.googleapis.com/storage/v1/b/mdb-latest/o/us-virginia-star-transit-flex-gtfs-2444.zip?alt=media"
    }
}

=== MobilityData/mobility-database-catalogs/catalogs/sources/gtfs/schedule/us-ohio-southwest-ohio-regional-transit-authority-sorta-metro-gtfs-366.json
{
    "mdb_source_id": 366,
    "data_type": "gtfs",
    "provider": "Southwest Ohio Regional Transit Authority (SORTA Metro)",
    "is_official": "True",
    "location": {
        "country_code": "US",
        "subdivision_name": "Ohio",
        "municipality": "Cincinnati",
        "bounding_box": {
            "minimum_latitude": 39.06428,
            "maximum_latitude": 39.35716,
            "minimum_longitude": -84.793912,
            "maximum_longitude": -84.259938,
            "extracted_on": "2022-03-15T21:17:37+00:00"
        }
    },
    "urls": {
        "direct_download": "https://www.go-metro.com/uploads/GTFS/google_transit_info.zip",
        "latest": "https://storage.googleapis.com/storage/v1/b/mdb-latest/o/us-ohio-southwest-ohio-regional-transit-authority-sorta-metro-gtfs-366.zip?alt=media"
    }
}

=== MobilityData/mobility-database-catalogs/catalogs/sources/gtfs/schedule/ie-unknown-national-transport-authority-gtfs-2364.json
{
    "mdb_source_id": 2364,
    "data_type": "gtfs",
    "provider": "Transport for Ireland (TFI)",
    "name": "Aggregate Ireland feed from National Transport Authority",
    "location": {
        "country_code": "IE",
        "bounding_box": {
            "minimum_latitude": 51.46855,
            "maximum_latitude": 55.37705,
            "minimum_longitude": -10.46157,
            "maximum_longitude": -5.93626793243424,
            "extracted_on": "2025-02-10T19:30:30+00:00"
        }
    },
    "urls": {
        "direct_download": "https://www.transportforireland.ie/transitData/Data/GTFS_All.zip",
        "authentication_type": 0,
        "latest": "https://storage.googleapis.com/storage/v1/b/mdb-latest/o/ie-unknown-national-transport-authority-gtfs-2364.zip?alt=media"
    },
    "redirect": []
}

=== MobilityData/mobility-database-catalogs/catalogs/sources/gtfs/schedule/us-oregon-coos-county-area-transit-ccat-gtfs-21.json
{
    "mdb_source_id": 21,
    "data_type": "gtfs",
    "provider": "Coos County Area Transit (CCAT)",
    "feed_contact_email": "support+test+cooscounty-or-us@trilliumtransit.com",
    "features": [
        "fares-v1"
    ],
    "location": {
        "country_code": "US",
        "subdivision_name": "Oregon",
        "municipality": "Coos Bay",
        "bounding_box": {
            "minimum_latitude": 42.87881944,
            "maximum_latitude": 43.982245,
            "minimum_longitude": -124.434431,
            "maximum_longitude": -123.345208,
            "extracted_on": "2022-03-14T20:06:40+00:00"
        }
    },
    "urls": {
        "direct_download": "https://oregon-gtfs.trilliumtransit.com/gtfs_data/cooscounty-or-us/cooscounty-or-us.zip",
        "authentication_type": 0,
        "latest": "https://storage.googleapis.com/storage/v1/b/mdb-latest/o/us-oregon-coos-county-area-transit-ccat-gtfs-21.zip?alt=media"
    },
    "redirect": []
}

=== MobilityData/mobility-database-catalogs/catalogs/sources/gtfs/schedule/us-arizona-douglas-city-of-douglas-gtfs-2864.json
{
  "mdb_source_id": 2864,
  "data_type": "gtfs",
  "provider": "City of Douglas",
  "location": {
    "country_code": "US",
    "bounding_box": {
      "minimum_latitude": null,
      "maximum_latitude": null,
      "minimum_longitude": null,
      "maximum_longitude": null,
      "extracted_on": "2025-10-30 18:02:52.236271+00:00"
    },
    "subdivision_name": "Arizona",
    "municipality": "Douglas"
  },
  "urls": {
    "direct_download": "https://rapid.nationalrtap.org/GTFSFileManagement/UserUploadFiles/13058/douglas_az_gtfs.zip",
    "latest": "https://storage.googleapis.com/storage/v1/b/mdb-latest/o/us-arizona-douglas-city-of-douglas-gtfs-2864.zip?alt=media",
    "authentication_type": 0
  },
  "feed_contact_email": "noelle.lievanos@douglasaz.gov",
  "features": [],
  "status": "active",
  "is_official": "True",
  "redirect": []
}

=== MobilityData/mobility-database-catalogs/catalogs/sources/gtfs/schedule/ca-ontario-toronto-transit-commission-gtfs-2253.json
{
    "mdb_source_id": 2253,
    "data_type": "gtfs",
    "provider": "Toronto Transit Commission (TTC)",
    "name": "Static feed for beta realtime feed",
    "is_official": "True",
    "status": "development",
    "location": {
        "country_code": "CA",
        "subdivision_name": "Ontario",
        "municipality": "Toronto",
        "bounding_box": {
            "minimum_latitude": 43.591811,
            "maximum_latitude": 43.909707,
            "minimum_longitude": -79.649908,
            "maximum_longitude": -79.123111,
            "extracted_on": "2022-03-16T22:08:44+00:00"
        }
    },
    "urls": {
        "direct_download": "https://ckan0.cf.opendata.inter.prod-toronto.ca/dataset/bd4809dd-e289-4de8-bbde-c5c00dafbf4f/resource/28514055-d011-4ed7-8bb0-97961dfe2b66/download/SurfaceGTFS.zip",
        "latest": "https://storage.googleapis.com/storage/v1/b/mdb-latest/o/ca-ontario-toronto-transit-commission-gtfs-2253.zip?alt=media"
    }
}

=== MobilityData/mobility-database-catalogs/catalogs/sources/gtfs/schedule/us-illinois-greater-peoria-mass-transit-citylink-gtfs-386.json
{
    "mdb_source_id": 386,
    "data_type": "gtfs",
    "provider": "Greater Peoria Mass Transit (CityLink)",
    "features": [
        "fares-v1"
    ],
    "status": "deprecated",
    "location": {
        "country_code": "US",
        "subdivision_name": "Illinois",
        "municipality": "Peoria",
        "bounding_box": {
            "minimum_latitude": 40.5385321,
            "maximum_latitude": 40.925506,
            "minimum_longitude": -89.694888,
            "maximum_longitude": -89.4816969907029,
            "extracted_on": "2022-03-16T15:27:32+00:00"
        }
    },
    "urls": {
        "direct_download": "http://data.trilliumtransit.com/gtfs/ridecitylink-il-us/ridecitylink-il-us.zip",
        "authentication_type": 0,
        "latest": "https://storage.googleapis.com/storage/v1/b/mdb-latest/o/us-illinois-greater-peoria-mass-transit-citylink-gtfs-386.zip?alt=media"
    },
    "redirect": [
        {
            "id": "2208",
            "comment": " "
        }
    ]
}

=== MobilityData/mobility-database-catalogs/catalogs/sources/gtfs/schedule/us-colorado-mountain-metro-transit-gtfs-2292.json
{
    "mdb_source_id": 2292,
    "data_type": "gtfs",
    "provider": "Mountain Metro Transit",
    "name": "Flex",
    "feed_contact_email": "support+coloradosprings-co-us@trilliumtransit.com",
    "location": {
        "country_code": "US",
        "subdivision_name": "Colorado",
        "municipality": "Colorado Springs",
        "bounding_box": {
            "minimum_latitude": 38.875356,
            "maximum_latitude": 38.875356,
            "minimum_longitude": -104.813228,
            "maximum_longitude": -104.813228,
            "extracted_on": "2024-11-27T22:42:08+00:00"
        }
    },
    "urls": {
        "direct_download": "https://data.trilliumtransit.com/gtfs/coloradosprings-co-us/coloradosprings-co-us--flex-v2.zip",
        "authentication_type": 0,
        "latest": "https://storage.googleapis.com/storage/v1/b/mdb-latest/o/us-colorado-mountain-metro-transit-gtfs-2292.zip?alt=media"
    },
    "redirect": []
}
